---
- name: Retrieve Kubeconfig
  hosts: k3s
  tasks:
    - name: Get Kubeconfig
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: $PWD/04_ansible/playbooks/kubeconfig/
        flat: yes
    - name: modify Kubeconfig
      copy:
        local_actions:
          - name: Replace localhost with ansible_host
            lineinfile:
              path: $PWD/04_ansible/playbooks/kubeconfig/k3s.yaml
              regexp: '{{              server:https://{{ ansible_host }}:6443 }}'
              line: '{{              server:https://{{ ansible_host }}:6443 }}'
              replace: '{{ ansible_host }}'
          - name: copy kubeconfig to ansible server
            copy:
              file: