---

- name: Créer le fichier Docker Compose pour Odoo
  ansible.builtin.copy:
    dest: /home/ubuntu/odoo-compose.yml
    content: |
      version: "3.9"
      services:
        db:
          image: postgres:15
          environment:
            POSTGRES_USER: odoo
            POSTGRES_PASSWORD: odoo
            POSTGRES_DB: odoo
          volumes:
            - odoo-db-data:/var/lib/postgresql/data

        odoo:
          image: odoo:16
          depends_on:
            - db
          ports:
            - "8069:8069"
          volumes:
            - odoo-data:/var/lib/odoo
          environment:
            HOST: db
            USER: odoo
            PASSWORD: odoo

      volumes:
        odoo-db-data:
        odoo-data:
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Nettoyer Docker system (cache, images, volumes orphelins)
  become: yes
  shell: |
    docker system prune -af
    docker volume prune -f

- name: Redémarrer Docker
  become: yes
  systemd:
    name: docker
    state: restarted

- name: Lancer la stack docker compose Odoo
  command: docker compose -f /home/ubuntu/odoo-compose.yml up -d
  args:
    chdir: /home/ubuntu


- name: Ouvrir le port 8069 dans le firewall
  ansible.builtin.ufw:
    rule: allow
    port: 8069
    proto: tcp
  when: ansible_facts['distribution'] == "Ubuntu"
