apiVersion: v1
kind: deployment
metadata:
  name: pgadmin-deploy
  namespace: icgroup
  labels:
    env: prod
    app: pgadmin
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        env: prod
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secret
                  key: pgadmin-configMap
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secret
                  key: postgres-password
      resources:
        requests: 
          memory: "128Mi"
          cpu: "500m"
          ports:
            - containerPort: 80
      volumeMounts:
        - name: pgadmin-storage
          mountPath: /pgadmin4/Server.json
          subPath: Server.json
        - name: pgadmin-storage-data
          mountPath: /var/lib/pgadmin
      volumes:
        - name: pgadmin-storage
          configMap:
          name: pgadmin-configMap
          items:
            - key: Server.json
              path: Server.json
          persistentVolumeClaim:
            claimName: pgadmin-pvc