apiVersion: v1
kind: Service
metadata:
  name: pgadmin-svc
  namespace: icgroup
  labels:
    env: prod
    app: pgadmin
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30011
  type: NodePort
  selector:
    env: prod
    app: pgadmin