apiVersion: v1
kind: Service
metadata:
  name: odoo-web-svc
  namespace: icgroup
  labels:
    env: prod
    app: odoo-web
spec:
  ports:
    - port: 8069
      targetPort: 8069
      nodePort: 30010
  selector:
    env: prod
    app: odoo-web