apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-pv
  namespace: icgroup
  labels:
    env: prod
    app: odoo-web
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: odoo-pv-storage
  hostPath:
    path: /data-odoo
