apiVersion: v1
kind: Service
metadata: 
  name: ic-webapp-svc
  namespace: icgroup
  labels:
    env: prod
    app: ic-webapp-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30009
  type: NodePort
  selector:
    app: ic-webapp