---
- name: Supprimer toutes les sources Docker conflictuelles
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - /etc/apt/sources.list.d/docker*
  become: yes

- name: Supprimer les anciennes clés Docker
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/trusted.gpg.d/docker.gpg
    - /etc/apt/keyrings/docker.gpg
  become: yes

- name: Supprimer le dossier des keyrings Docker (s'il existe)
  file:
    path: /etc/apt/keyrings
    state: absent
  become: yes

- name: Recréer le dossier keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes

- name: Installer les prérequis APT
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
  become: yes

- name: Télécharger la clé GPG officielle Docker
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.gpg
    mode: '0644'
  become: yes

- name: Ajouter le dépôt Docker stable
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    filename: docker
    state: present
  become: yes

- name: Mettre à jour la liste des paquets
  apt:
    update_cache: yes
  become: yes

- name: Installer Docker CE, CLI, containerd et docker-compose-plugin
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
  become: yes

- name: S’assurer que Docker est démarré et activé
  service:
    name: docker
    state: started
    enabled: yes
  become: yes
