---
- name: Supprimer anciennes sources Docker potentiellement conflictuelles
  file:
    path: "/etc/apt/sources.list.d/docker.list"
    state: absent
  become: yes

- name: Créer dossier pour keyrings si absent
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes

- name: Télécharger la clé GPG officielle Docker
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.gpg
    mode: '0644'
  become: yes

- name: Ajouter le dépôt Docker officiel avec signed-by
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu focal stable"
    state: present
  become: yes

- name: Mettre à jour la liste des paquets apt
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: Installer Docker et containerd
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: no
  become: yes

- name: S’assurer que Docker est démarré et activé
  service:
    name: docker
    state: started
    enabled: yes
  become: yes
