services:
  ic-webapp:
    container_name: ic-webapp
    ports: 
      - 8080:8080
    image: ic-webapp:1.0
    environment:
      - "ODOO_URL=http://35.180.251.100:8069/"
      - "PGADMIN_URL=http://35.180.251.100:80"