---
- name: Déployer le conteneur Docker de l'application
  hosts: all
  become: yes
  vars:
    ic_webapp_port: 8080
    odoo_url: "http://35.180.251.100:8069/"
    pgadmin_url: "http://35.180.251.100:80"

  roles:
    - docker

  tasks:
    - name: Pull de la dernière image Docker depuis GHCR
      docker_image:
        name: ghcr.io/{{ lookup('env', 'GITHUB_REPOSITORY_OWNER') }}/ic-webapp
        tag: latest
        source: pull

    - name: Stopper et supprimer le conteneur existant
      docker_container:
        name: monapp
        state: absent
        force_kill: yes
      ignore_errors: yes

    - name: Lancer le conteneur Docker
      docker_container:
        name: monapp
        image: ghcr.io/{{ lookup('env', 'GITHUB_REPOSITORY_OWNER') }}/ic-webapp:latest
        state: started
        restart_policy: always
        ports:
          - "{{ ic_webapp_port }}:8080"
        env:
          ODOO_URL: "{{ odoo_url }}"
          PGADMIN_URL: "{{ pgadmin_url }}"
