---
- name: Supprimer les anciennes sources Docker conflictuelles
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/sources.list.d/docker.list
    - /etc/apt/sources.list.d/docker.list.save
    - /etc/apt/sources.list.d/docker.list.distUpgrade
    - /etc/apt/sources.list.d/docker.list.disabled
    - /etc/apt/sources.list.d/docker-ce.list
    - /etc/apt/sources.list.d/docker-ce.list.save
    - /etc/apt/sources.list.d/docker-ce.list.distUpgrade
    - /etc/apt/sources.list.d/docker-ce.list.disabled

- name: Supprimer anciennes clés GPG Docker
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/trusted.gpg.d/docker.gpg
    - /etc/apt/keyrings/docker.gpg

- name: Installer les paquets requis
  become: yes
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Créer le dossier keyrings (si absent)
  become: yes
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Télécharger et ajouter la clé GPG officielle Docker
  become: yes
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.gpg
    mode: '0644'

- name: Ajouter le dépôt Docker stable
  become: yes
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present
    filename: docker

- name: Mettre à jour la liste des paquets
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Installer Docker CE, CLI, containerd et docker-compose-plugin
  become: yes
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present

- name: Vérifier la version de Docker installée
  become: yes
  command: docker --version
  register: docker_version
  changed_when: false

- name: Afficher la version Docker
  debug:
    msg: "Docker version: {{ docker_version.stdout }}"
