---
- name: Supprimer toutes les sources Docker existantes conflictuelles
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - /etc/apt/sources.list.d/docker*
  become: yes

- name: Supprimer les lignes Docker dans /etc/apt/sources.list
  lineinfile:
    path: /etc/apt/sources.list
    regexp: '^deb .*download.docker.com'
    state: absent
  become: yes

- name: Supprimer les anciennes clés Docker
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/trusted.gpg.d/docker.gpg
    - /etc/apt/keyrings/docker.gpg
  become: yes

- name: Supprimer le dossier des keyrings Docker (si présent)
  file:
    path: /etc/apt/keyrings
    state: absent
  become: yes

- name: Recréer le dossier keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes

- name: Télécharger la clé GPG Docker officielle
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.gpg
    mode: '0644'
  become: yes

- name: Ajouter le dépôt Docker officiel avec signed-by
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu focal stable"
    filename: docker
    state: present
  become: yes

- name: Vérifier le contenu du fichier docker.list
  ansible.builtin.shell: cat /etc/apt/sources.list.d/docker.list
  register: docker_repo
  changed_when: false

- name: Afficher le dépôt Docker configuré
  ansible.builtin.debug:
    var: docker_repo.stdout

- name: Mettre à jour la liste des paquets apt
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: Installer Docker CE, CLI et containerd
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  become: yes

- name: S’assurer que Docker est démarré et activé
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
  become: yes