---
- name: Déploiement application avec Docker
  hosts: ec2-cible
  become: true

  tasks:
    - name: Supprimer toute ancienne version de Docker
      apt:
        name:
          - docker.io
          - docker-doc
          - docker-compose
          - podman-docker
          - containerd
          - runc
        state: absent

    - name: Installer prérequis apt
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Ajouter la clé GPG officielle de Docker
      shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Ajouter le dépôt Docker officiel
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

    - name: Installer Docker CE et Docker Compose V2
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: S'assurer que Docker est démarré et activé
      service:
        name: docker
        state: started
        enabled: yes

    - name: Lancer la stack avec Docker Compose V2
      community.docker.docker_compose_v2:
        project_src: /chemin/vers/ton/docker-compose
        remove_orphans: yes
