---
- name: Installer dépendances pour Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Créer le dossier pour les clés GPG
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Ajouter la clé GPG officielle Docker
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.gpg
    mode: '0644'

- name: Convertir la clé en format gpg
  shell: gpg --dearmor < /etc/apt/keyrings/docker.gpg > /etc/apt/keyrings/docker.gpg.tmp && mv /etc/apt/keyrings/docker.gpg.tmp /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Ajouter le dépôt officiel Docker
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
      deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    mode: '0644'

- name: Installer Docker Engine et Compose V2
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: S'assurer que Docker est démarré et activé
  service:
    name: docker
    state: started
    enabled: true
