---
- name: Supprimer anciennes clés Docker (pour éviter conflit)
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/trusted.gpg.d/docker.gpg
    - /etc/apt/keyrings/docker.gpg

- name: Créer le dossier keyrings
  become: yes
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Télécharger la clé GPG Docker officielle dans keyrings
  become: yes
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.gpg
    mode: '0644'

- name: Ajouter le dépôt Docker stable avec signed-by sur clé Docker
  become: yes
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present
    filename: docker

- name: Mettre à jour la liste des paquets APT
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Installer Docker CE et dépendances
  become: yes
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
