---
# ===================================================================
# Rôle Docker - Installation Docker
# ===================================================================

# 1. Nettoyage complet des anciennes configurations
- name: Supprimer toutes les entrées Docker dans /etc/apt/sources.list.d/
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - /etc/apt/sources.list.d/*docker*
    - /etc/apt/sources.list.d/*Docker*
  become: yes

- name: Supprimer les lignes Docker du sources.list principal
  lineinfile:
    path: /etc/apt/sources.list
    regexp: '^.*download\.docker\.com.*$'
    state: absent
  become: yes

- name: Supprimer toutes les anciennes clés Docker
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/trusted.gpg.d/docker.gpg
    - /etc/apt/keyrings/docker.gpg
  become: yes

- name: Vider le cache APT après nettoyage
  command: apt-get clean
  become: yes

# 2. Création du dossier keyrings
- name: Créer le dossier keyrings si absent
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes

# 3. Installation des prérequis
- name: Installer les prérequis pour Docker
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
  become: yes

# 4. Ajout de la clé GPG officielle Docker
- name: Ajouter la clé GPG officielle Docker
  ansible.builtin.shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg
  become: yes

# 5. Ajout du dépôt Docker officiel
- name: Ajouter le dépôt Docker stable
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present
    filename: docker
    update_cache: yes
  become: yes

# 6. Installation de Docker et docker-compose-plugin
- name: Installer Docker Engine et docker-compose-plugin
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: yes
  become: yes

# 7. Vérification des versions
- name: Vérifier la version de Docker
  command: docker --version
  register: docker_version
  changed_when: false

- name: Vérifier la version de docker compose
  command: docker compose version
  register: docker_compose_version
  changed_when: false
