---
# Nettoyage complet des dépôts et clés Docker existants
- name: Supprimer tous les fichiers sources Docker
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - /etc/apt/sources.list.d/docker*
  become: yes

- name: Supprimer les anciennes clés Docker
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/trusted.gpg.d/docker.gpg
    - /etc/apt/keyrings/docker.gpg
  become: yes

- name: Créer le dossier keyrings si absent
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes

# Installation des prérequis
- name: Installer les prérequis pour Docker
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
  become: yes

# Clé GPG officielle Docker
- name: Télécharger la clé GPG officielle Docker
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.gpg
    mode: '0644'
  become: yes

# Dépôt officiel Docker
- name: Ajouter le dépôt Docker stable
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    filename: docker
    state: present
  become: yes

# Mise à jour et installation
- name: Mettre à jour la liste des paquets apt
  apt:
    update_cache: yes
  become: yes

- name: Installer Docker et Compose
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
  become: yes

- name: S’assurer que Docker est démarré et activé
  service:
    name: docker
    state: started
    enabled: yes
  become: yes
