---
- name: Supprimer toute installation Docker APT existante (docker.io, containerd, runc)
  apt:
    name:
      - docker.io
      - containerd
      - runc
    state: absent
    purge: yes
  become: yes

- name: Nettoyer les paquets cassés et dépendances inutiles
  shell: |
    apt-get clean
    apt-get autoremove -y
    apt-get -f install -y
  become: yes

- name: Installer dépendances pour dépôt Docker
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
  become: yes

- name: Ajouter clé GPG Docker
  shell: |
    mkdir -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg
  become: yes

- name: Ajouter dépôt Docker officiel
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    filename: docker
    state: present
  become: yes

- name: Installer docker-ce et containerd depuis dépôt officiel
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: yes
  become: yes
