---
# Nettoyage complet avant installation
- name: Supprimer tous les dépôts Docker (sources.list.d)
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - /etc/apt/sources.list.d/*docker*
    - /etc/apt/sources.list.d/*Docker*
  become: yes

- name: Purger les lignes Docker dans /etc/apt/sources.list
  lineinfile:
    path: /etc/apt/sources.list
    regexp: '^.*download\.docker\.com.*$'
    state: absent
  become: yes

- name: Supprimer les anciennes clés Docker
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/trusted.gpg.d/docker.gpg
    - /etc/apt/keyrings/docker.gpg
  become: yes

# Installation Docker officielle
- name: Créer le dossier keyrings si absent
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes

- name: Installer les prérequis pour Docker
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
  become: yes

- name: Ajouter la clé GPG officielle Docker
  ansible.builtin.command:
    cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg
  become: yes

- name: Définir les permissions de la clé Docker
  file:
    path: /etc/apt/keyrings/docker.gpg
    mode: '0644'
  become: yes

- name: Ajouter le dépôt Docker stable
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present
    filename: docker
    update_cache: yes
  become: yes

- name: Installer Docker Engine et plugins
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes
  become: yes

# Vérifications
- name: Vérifier la version de Docker
  command: docker --version
  register: docker_version
  changed_when: false

- name: Afficher la version de Docker
  debug:
    var: docker_version.stdout
