---
- name: Mettre à jour le cache apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Installer les dépendances nécessaires
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg-agent
      - containerd
    state: present

- name: Ajouter la clé GPG officielle Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Ajouter le dépôt Docker stable
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
    update_cache: yes

- name: Installer Docker CE
  apt:
    name: docker-ce
    state: latest

- name: Assurer que Docker est démarré et activé
  service:
    name: docker
    state: started
    enabled: yes
