---
- name: Installer Docker si nécessaire
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: S’assurer que Docker est démarré et activé
  service:
    name: docker
    state: started
    enabled: yes
