---
# Nettoyage complet des anciennes installations Docker
- name: Supprimer tous les dépôts Docker restants
  shell: |
    rm -f /etc/apt/sources.list.d/*docker*
    rm -f /etc/apt/sources.list.d/*Docker*
  args:
    warn: false
  become: yes

- name: Supprimer les lignes Docker du sources.list principal
  lineinfile:
    path: /etc/apt/sources.list
    regexp: '^.*download\.docker\.com.*$'
    state: absent
  become: yes

- name: Supprimer toutes les anciennes clés Docker
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/trusted.gpg.d/docker.gpg
    - /etc/apt/keyrings/docker.gpg
  become: yes

- name: Vider le cache et forcer mise à jour des paquets
  shell: |
    apt-get clean
    apt-get update || true
  become: yes

# Installation Docker
- name: Créer le dossier keyrings si absent
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes

- name: Installer les prérequis pour Docker
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
  become: yes

- name: Ajouter la clé GPG officielle Docker
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg
  become: yes

- name: Ajouter le dépôt Docker stable
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present
    filename: docker
  become: yes

- name: Installer Docker Engine et docker-compose-plugin
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: yes
  become: yes

- name: Vérifier la version de Docker
  command: docker --version
  register: docker_version
  changed_when: false

- name: Vérifier la version de docker compose
  command: docker compose version
  register: docker_compose_version
  changed_when: false
