apiVersion: v1
kind: deployment
metadata: 
  name: postgres-deploy
  namespace: icgroup
  labels:
    env: prod
    app: postgres 
spec:

  replicas: 1
  selector:
    matchLabels:
      env: prod
      app: postgres
  template:
    metadata:
      labels:
        env: prod
        app: postgres
    spec:
      containers:
        - name: postgres-container
          image: postgres:15
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-ConfigMap
                  key: user
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-ConfigMap
                  key: database
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-ConfigMap
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data/pgdatabase
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc