apiVersion: v1
kind: persistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: icgroup
  labels:
    env: prod
    app: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Adjust storage size as needed     