name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # ==== CI: Build & Push Docker Image ====
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        run: |
          owner=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$owner/ic-webapp:latest ./webapp-builder
          docker push ghcr.io/$owner/ic-webapp:latest

  # ==== CD: Deploy via Ansible ====
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run deploy-full.yml
        run: |
          ansible-playbook ansible-playbooks/deploy-full.yml \
            -i ansible-playbooks/inventory.ini \
            --private-key ~/.ssh/id_rsa
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
