name: CI/CD Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get lowercase repo owner
        id: vars
        run: echo "OWNER_LOWER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          echo "Using owner: ${{ steps.vars.outputs.OWNER_LOWER }}"
          docker build -t ghcr.io/${{ steps.vars.outputs.OWNER_LOWER }}/ic-webapp:latest ./webapp-builder
          docker push ghcr.io/${{ steps.vars.outputs.OWNER_LOWER }}/ic-webapp:latest
  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python and Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible paramiko

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 host to known_hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Run consolidated Ansible playbook
        run: |
          cd ansible-playbooks
          ansible-playbook -i ansible-inventory.yml deploy-stack.yml
