name: CI/CD Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies (ansible, paramiko, etc.)
        run: |
          python -m pip install --upgrade pip
          pip install ansible paramiko

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
          
      - name: Add EC2 host to known_hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Create target directory on EC2
        run: ssh ubuntu@${{ secrets.EC2_HOST }} "mkdir -p /home/ubuntu/app"

      - name: Copy application files to EC2
        run: |
          scp -r ./ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/app/

      - name: List ansible-playbooks directory for debug
        run: ls -R ansible-playbooks

      - name: Run Ansible Playbook
        run: |
         cd ansible-playbooks
         ansible-playbook -i ansible-inventory.yml playbook/deploy-stack.yml
