 all:
  hosts:
    ec2-cible:
      ansible_host: 35.180.251.100
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
  vars:
    ic_webapp_port: 8080
    ic_webapp_version: "1.0"
    odoo_url: "http://35.180.251.100:8069/"
    pgadmin_url: "35.180.251.100:80"